### ISSUE TITLE
Get Mobile Details

### ISSUE THREAD

**Issue by Mrjoy832** [TusharAMD/Runn#239]
I want to add an application which will get all details of any Mobile number  using Python
@TusharAMD Kindly assign

**Comment by TusharAMD** [comment]
Can you please elaborate. I am wondering how it can be implemented as game

**Comment by Mrjoy832** [comment]
> Can you please elaborate. I am wondering how it can be implemented as game

it's not exact game..here by giving input of any ph number...it will give details of SIM owner, Location, SIM type

---
## Kindly add GSSOC label in my merged PR
https://github.com/TusharAMD/Runn/pull/232

**Comment by TusharAMD** [comment]
Added gssoc in #232. 
And about this one I think it won't match requirements of this repo. It is more of utility tool and here we are trying to create games which can be played by gestures.
