### ISSUE TITLE
Chess game controlled by gestures (Game)

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#24]
- Make a new folder in games directory (If not already present). 
- Use any language/framework of your choice to make the chess game. 
- Add Screenshot and Readme
Readme can include 
1. Title
2. What the Project Does.
3. How to use.
4. How to install or requirements
5. Screenshots

**Comment by aritra1804** [comment]
Hey I would like to work on this issue for gssoc 22, pls assign me this issue

**Comment by TusharAMD** [comment]
Assigned
