### ISSUE TITLE
Heart Disease Classifier using Flask and ML

### ISSUE THREAD

**Issue by AnIkeT126** [TusharAMD/Runn#258]
**Heart Disease Classifier using Flask and ML**

**Comment by AnIkeT126** [comment]
@TusharAMD please assign this to me

**Comment by TusharAMD** [comment]
No we aren't making projects like this one. We are creating games and then it can be played using gestures

**Comment by AnIkeT126** [comment]
> No we aren't making projects like this one. We are creating games and then it can be played using gestures

only python based or HTML, CSS and js also allowed??
