### ISSUE TITLE
Soduku (Game)

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#26]
- Make a new folder in games directory (If not already present). 
- Use any language/framework of your choice to make the game. 
- Add Screenshot and Readme
Readme can include 
1. Title
2. What the Project Does.
3. How to use.
4. How to install or requirements
5. Screenshots

**Comment by khandagalechetna** [comment]
Please assign it to me under GSSOC'22

**Comment by TusharAMD** [comment]
Assigned @khandagalechetna

**Comment by chetnaakhandagale** [comment]
Hey @TusharAMD, We can close this as I have already added all the files in the folder named Games.

**Comment by TusharAMD** [comment]
Done
