### ISSUE TITLE
Car Racing (game)

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#27]
- Make a new folder in games directory (If not already present). 
- Use any language/framework of your choice to make the game. 
- Add Screenshot and Readme
Readme can include 
1. Title
2. What the Project Does.
3. How to use.
4. How to install or requirements
5. Screenshots

**Comment by codervivek5** [comment]
I want to work on this issue under Gssoc'22

**Comment by TusharAMD** [comment]
Ok assigned @codervivek5

**Comment by aritra1804** [comment]
@TusharAMD pls assign me this issue for gssoc 22. It would be easier for me as i have already added gesture control for this. Also its been a month since this issue has been assigned

**Comment by aritra1804** [comment]
@TusharAMD pls close this issue as pr is merged
