### ISSUE TITLE
Paman Game

### ISSUE THREAD

**Issue by AnIkeT126** [TusharAMD/Runn#275]
classic arcade game. Use the arrow keys to navigate and eat all the white food. Watch out for red ghosts that roam the maze.

Yellow  bol is us and red our enemies

**Comment by AnIkeT126** [comment]
@TusharAMD please assign this to me

**Comment by LiQuiD-404** [comment]
@AnIkeT126 I am already working on this issue #210

**Comment by AnIkeT126** [comment]
> @AnIkeT126 I am already working on this issue #210

okhh
