### ISSUE TITLE
reorganised the project and included some files 

### ISSUE THREAD

**Issue by jhonsnow456** [TusharAMD/Runn#3]
The project misses .gitignore file a README.
Removal of cache folder  needed as __pycache__ .
project need to be reorganised a bit

**Comment by jhonsnow456** [comment]
https://github.com/TusharAMD/Runn/pull/2#issue-1150286855 here is the PR which will solve this issue.

**Comment by TusharAMD** [comment]
Pull Request Merged Successfully 🎉
