### ISSUE TITLE
Soduku (Ideation)

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#33]
Make a new folder in games directory and add Markdown file with idea

**Comment by learner2102** [comment]
Assign me this issue.

**Comment by aritra1804** [comment]
@TusharAMD pls assign me this isssue

**Comment by Pushpita05** [comment]
@TusharAMD Hey, I would like to work on this for gssoc 22, kindly assign to me

**Comment by TusharAMD** [comment]
Assigned

**Comment by aritra1804** [comment]
@TusharAMD plss close this issue as pr is merged
