### ISSUE TITLE
Spot the Colors

### ISSUE THREAD

**Issue by AnIkeT126** [TusharAMD/Runn#419]
Paint game in python

**Comment by AnIkeT126** [comment]
@TusharAMD please assign

**Comment by TusharAMD** [comment]
![image](https://user-images.githubusercontent.com/59115865/170451509-ffb3a961-3438-4450-9ae0-af00e412b868.png)
@Mrjoy832 has made a issue with same name. Let's check what he does and if your approach is different I will assign.

**Comment by AnIkeT126** [comment]
@TusharAMD mine is like, paint ball kind of setup that u must have seen in the big bang theory

**Comment by TusharAMD** [comment]
Assigned for now. Lets see what @Mrjoy832 has to say something

**Comment by Mrjoy832** [comment]
> Assigned for now. Lets see what @Mrjoy832 has to say something

he has changed the issue..now it's fine
