### ISSUE TITLE
Hit me toy - Core game

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#556]
More harder you air punch more points you get from hit me toy

**Comment by AbhineshJha** [comment]
hey ! @TusharAMD I wanna work in this issue.. Can u assign me with this issue ??

**Comment by Bayyana-kiran** [comment]
hey @AbhineshJha can u assign me ?

**Comment by AbhineshJha** [comment]
Sorry bro @Bayyana-kiran  i am not the maintainer of this repo ,
the maintainer is @TusharAMD

**Comment by Bayyana-kiran** [comment]
Oh okay bro chill....I have seen in the leaderboard...u r god level bro 🔥🔥🔥...keep up the work

**Comment by AbhineshJha** [comment]
thank uh @Bayyana-kiran !!😊
