### ISSUE TITLE
Ladoo Catcher - Gesture

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/Runn#560]

**Comment by hemant933** [comment]
sir , can u provide me some reference what u want

**Comment by TusharAMD** [comment]
@hemant933 In this game idea was to create a game where the character would catch ladoos falling from sky. There would be also some non edible items like paper or stone which we should avoid. But this is just suggestion, you can design anything you think would be appropriate for this theme.

**Comment by hemant933** [comment]
Cool, I'll check it out.

**Comment by hemant933** [comment]
assign it to me

**Comment by hemant933** [comment]
sir , i am working on this game and as well as its documentation

**Comment by TusharAMD** [comment]
Ok assigned
