### ISSUE TITLE
want to add breakout game (GAME)

### ISSUE THREAD

**Issue by iamrahulmahato** [TusharAMD/Runn#97]
2D Breakout Game using HTML, CSS and JavaScript.

SS:
![Web capture_2-5-2022_181452_127 0 0 1](https://user-images.githubusercontent.com/49890655/166613597-69d0e536-93f7-4d9a-b1ab-87c9b01200ce.jpeg)

**Comment by iamrahulmahato** [comment]
I want to work on this issue under Gssoc'22

**Comment by TusharAMD** [comment]
@iamrahulmahato Assigned

**Comment by iamrahulmahato** [comment]
@TusharAMD the pr is made #100
